# Generated by Django 3.1.3 on 2021-08-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newjogging',
            name='price',
            field=models.IntegerField(blank=True),
        ),
    ]
