# Generated by Django 3.1.3 on 2021-08-12 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_commentjogging'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentjogging',
            name='author',
        ),
        migrations.AddField(
            model_name='commentjogging',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='community.newjogging'),
            preserve_default=False,
        ),
    ]
