# Generated by Django 3.1.3 on 2021-08-12 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0004_commentjogging_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentjogging',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='community.newjogging'),
        ),
    ]
